#!/usr/bin/python
## pwfr - python weather forecast reporter
## vim: ft=python ts=4 sw=4 et:

#*   Open Source software - copyright and GPLv2 apply. Briefly:       *
#*    - No warranty/guarantee of fitness, use is at own risk          *
#*    - No restrictions on strictly-private use/copying/modification  *
#*    - No re-licensing this work under more restrictive terms        *
#*    - Redistributing? Include/offer to deliver original source      *
#*   Philosophy/full details at http://www.gnu.org/copyleft/gpl.html  *

import getopt, sys
import bbcreader
import curses
from threading import Timer


default_delaymins= 5

def tui_loop(stdscr, fr, delaysec=5):
    tui_loop.timer= None

    def tui_quit():
        tui_loop.timer.cancel()
        sys.exit(1)

    def tui_update(scr):
        dwin_title.erase()
        dwin_title.addstr(0,25, "Python Weather Forecast Reader")
        dwin_title.noutrefresh()

        dwin_now.clear()
        #fr.readCache()
        fr.readRSS()
        fr.process()
        if len(fr.forecast) == 0:
            dwin_now.addstr(1,0, fr.getStatus())	## displays error
        else:
            for item in fr.forecast:
                dwin_now.addstr("\n")
                dwin_now.addstr("%s\n" %(item["title"]))
                if item["temp.now"]:
                    dwin_now.addstr("Temp: %s\n" %(item["temp.now"]))
                else:
                    dwin_now.addstr("Temp: %s to %s\n" %(item["temp.min"], item["temp.max"]))
                dwin_now.addstr("Press: %s\n" %(item["pressure.level"]))
                dwin_now.addstr("Wind dir: %s\n" %(item["wind.direction"]))
                dwin_now.addstr("Wind speed: %s\n" %(item["wind.speed"]))
        dwin_now.noutrefresh()

        dwin_status.erase()
        dwin_status.addstr(0,32, "Press Q to quit")
        dwin_status.noutrefresh()

        curses.doupdate()
        #scr.refresh()

        if tui_loop.timer is not None:
            tui_loop.timer.cancel()
        tui_loop.timer= Timer(delaysec, tui_update, [scr])
        tui_loop.timer.start()


    ## tui_loop main body
    global dwin_title, dwin_now, dwin_status
    global scr_h,scr_w
    scr_h, scr_w= stdscr.getmaxyx()
    dwin_title= stdscr.derwin(1,scr_w,0,0)
    dwin_now= stdscr.derwin(scr_h-2,scr_w,1,0)
    dwin_status= stdscr.derwin(1,scr_w,scr_h-1,0)
    tui_update(stdscr)
    stdscr.keypad(1)
    while 1:
        try:
            ch= stdscr.getch()
        except:
            tui_quit()

        if ch == ord('q'):
            tui_quit()
        else:
            tui_update(stdscr)


    if tui_loop.timer is not None:
        tui_loop.timer.cancel()

def usage(message=None):
    if message:
        print(message)
    else:
        print("This is 'pwfr', the python weather forecast reporter")
    print
    print("Usage:")
    print("\t%s [OPTIONS] LOCATION" %(sys.argv[0]))
    print
    print("Options:")
    print("\t-h, --help: show this help")
    print("\t--delay <n>: refresh UI after <n> minutes (default %d)" %(default_delaymins))
    print("\t--noui: show report without engaging UI")

if __name__ == "__main__":
    delaymins= default_delaymins
    show_ui= True

    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help", "delay=", "noui"])
    except getopt.GetoptError as oe:
        usage("Error in options: %s" %(oe.msg))
        sys.exit(1)

    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage()
            sys.exit()
        elif opt in ('--delay'):
            delaymins= int(arg)
        elif opt in ('--noui'):
            show_ui= False

    if len(args) == 0:
        usage("ERROR: Expected a location argument")
        sys.exit(1)
    elif len(args) > 1:
        usage("ERROR: Only one location expected")
        sys.exit(1)
    else:
        fr= bbcreader.BBCReader(args[0])
        fr.readRSS()
        #fr.readCache()
        if show_ui:
            curses.wrapper(tui_loop, fr, delaymins * 60)
        else:
            print(fr.getSummary())
