#!/usr/bin/python
## pwfr - python weather forecast reporter
## vim: ft=python ts=4 sw=4 et:

#*   Open Source software - copyright and GPLv2 apply. Briefly:       *
#*    - No warranty/guarantee of fitness, use is at own risk          *
#*    - No restrictions on strictly-private use/copying/modification  *
#*    - No re-licensing this work under more restrictive terms        *
#*    - Redistributing? Include/offer to deliver original source      *
#*   Philosophy/full details at http://www.gnu.org/copyleft/gpl.html  *

import getopt, sys
import bbcreader

def usage():
    print("This is 'pwfr', the python weather forecast reporter")
    print
    print("Usage:")
    print("\t%s OPTIONS LOCATION" %(sys.argv[0]))
    print
    print("Options:")
    print("\t-h, --help: show this help")

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help", "noui"])
    except getopt.GetoptError:
        usage()
        sys.exit(1)

    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage()
            sys.exit()

    if len(args) == 0:
        usage()
    elif len(args) > 1:
        print("Invalid location, or too many arguments")
        usage()
        sys.exit(1)
    else:
        fr= bbcreader.BBCReader(args[0])
        fr.readRSS()
        print(fr.getReport())
